site_name: "Silicon Sprint AUC Workshop"
repo_url: "https://github.com/basemhesham/Silicon-Sprint-AUC"

theme:
  name: material
  features:
    - content.code.copy  
    - navigation.sections
    - content.code.annotate

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - attr_list 
