site_name: "Silicon Sprint AUC Workshop"
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo

nav:
  - Home: index.md
  - Installation: MODULE0.md
  - RTL Exploration: MODULE1.md

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true 
  - pymdownx.inlinehilite
